### ISSUE TITLE
“没有找到Dolphin 3.5 模拟器配置文件，请先关闭模拟器再重新打开本程序”

### ISSUE THREAD

**Issue by mccrena** [hegeo/JustdancePCSE#2]
rt，系统是win11 22H2，请问是不支持win11吗

**Comment by hegeo** [comment]
支持的，可能得具体看一下

**Comment by mccrena** [comment]
![image](https://user-images.githubusercontent.com/95366235/194750702-61e05341-884f-4118-a200-8c9febaa8c5c.png)
![image](https://user-images.githubusercontent.com/95366235/194750706-98ae6c33-35bb-4356-b1dc-6d491df0eb1f.png)
之前没有下过dolphin模拟器，然后直接下了您的文件，双击启动器文件打开就是这个弹窗，右侧的是我另外单独下载的dolphin模拟器，现在正在用joycon模拟wii双截棍游玩，还是希望您能给个思路，那个弹窗因为我对dolphin不是很了解，不清楚什么意思

**Comment by hegeo** [comment]
我这里是win10系统，不清楚win11路径有没有变，使用这个启动器，最好使用启动器自带的模拟器，
一般情况下第一次打开会自动启动模拟器，提示找不到配置文件，关闭提示和模拟器，再次打开即可，
如果还是这个提示，看看模拟器配置文件的路径，是否为 \Documents\Dolphin Emulator\Config\Dolphin.in

**Comment by hegeo** [comment]
如果还是不行可以修改源代码编译一下哦

**Comment by hegeo** [comment]
你好，JustdancePCSE现已更新v2.0，欢迎体验，麻烦点点★ star


hegeo/JustdancePCSE: 舞力全开特别版启动器，实现模拟器自动配置和安卓体感游玩，Justdance PC Launcher，Implementing emulator auto-configuration and Android app (github.com)




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hegeo/JustdancePCSE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月9日(星期天) 晚上6:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hegeo/JustdancePCSE] “没有找到Dolphin 3.5 模拟器配置文件，请先关闭模拟器再重新打开本程序” (Issue #2)





 

 
 之前没有下过dolphin模拟器，然后直接下了您的文件，双击启动器文件打开就是这个弹窗，右侧的是我另外单独下载的dolphin模拟器，现在正在用joycon模拟wii双截棍游玩，还是希望您能给个思路，那个弹窗因为我对dolphin不是很了解，不清楚什么意思
